--- a/.github/workflows/ci-5.x.yml
+++ b/.github/workflows/ci-5.x.yml
@@ -37,9 +37,9 @@
     secrets: inherit
   Deploy:
     if: ${{ github.repository_owner == 'eclipse-vertx' && (github.event_name == 'push' || github.event_name == 'schedule') }}
-    needs: Test
+    needs: CI
     uses: ./.github/workflows/ci.yml
     with:
       branch: ${{ github.head_ref || github.ref_name }}
       jdk: 8
-    secrets: inherit
+    secrets: inherit